name: Build Stage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.1.0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install virtualenv
        virtualenv ./.virtualenv
        source ./.virtualenv/bin/activate
        pip install -r requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Update Environment
      run: |
        cp ./.environments/stage.yaml ./zappa_settings.yaml
        source ./.virtualenv/bin/activate
        zappa update stage || RESULT=`echo $?`
        if [ $RESULT = 0 ] || [ $RESULT = 1 ]
        then
          echo "OK"
        else
          exit 1
        fi